INSERT INTO parking_slots (slot_number, vehicle_type, status)
VALUES
('B01', 'TWO_WHEELER', 'AVAILABLE'),
('B02', 'TWO_WHEELER', 'AVAILABLE'),
('B03', 'TWO_WHEELER', 'OCCUPIED'),
('B04', 'TWO_WHEELER', 'AVAILABLE'),
('B05', 'TWO_WHEELER', 'RESERVED'),
('B06', 'TWO_WHEELER', 'AVAILABLE'),
('B07', 'TWO_WHEELER', 'AVAILABLE'),
('B08', 'TWO_WHEELER', 'OCCUPIED'),
('B09', 'TWO_WHEELER', 'AVAILABLE'),
('B10', 'TWO_WHEELER', 'AVAILABLE');

INSERT INTO parking_slots (slot_number, vehicle_type, status)
VALUES
('A01', 'FOUR_WHEELER', 'AVAILABLE'),
('A02', 'FOUR_WHEELER', 'RESERVED'),
('A03', 'FOUR_WHEELER', 'AVAILABLE'),
('A04', 'FOUR_WHEELER', 'OCCUPIED'),
('A05', 'FOUR_WHEELER', 'AVAILABLE'),
('A06', 'FOUR_WHEELER', 'AVAILABLE'),
('A07', 'FOUR_WHEELER', 'RESERVED'),
('A08', 'FOUR_WHEELER', 'AVAILABLE');

INSERT INTO parking_slots (slot_number, vehicle_type, status)
VALUES
('H01', 'HEAVY_VEHICLE', 'AVAILABLE'),
('H02', 'HEAVY_VEHICLE', 'OCCUPIED'),
('H03', 'HEAVY_VEHICLE', 'AVAILABLE'),
('H04', 'HEAVY_VEHICLE', 'AVAILABLE');